### PR TITLE
Upgrade frunk from v0.3.1 to v0.4.0

### PR DESCRIPTION
**Pull request by aburkhalter512**
Bumps frunk to a much more recent version.

I also fixed some broken doc tests and cleaned up some formatting in the process. I'm not sure how you are versioning teloc, but I bumped the version numbers in a PR since the frunk upgrade has some breaking changes for anyone who is using `teloc::reexport` downstream. Let me know if anything looks off or needs changing

### CODE REVIEW

**Comment by aburkhalter512** [comment]
@p0lunin Let me know if you want me to split this commits up into separate PRs for faster review

**Comment by p0lunin** [comment]
@aburkhalter512 I don't know clippy upgrade produce errors or it is my fault i have not check code before, but can you fix it in this PR?
I'll check changes some later.

**Comment by aburkhalter512** [comment]
@p0lunin Not sure where to ask this, but are you going to publish version 0.2.0 soon? I'd like to use it in another project but can't because of the old transitive deps in 0.1.0

**Comment by p0lunin** [comment]
@aburkhalter512 I think I can do it, but I need to fix one minor bug.
You can use teloc from master branch for now, and when i will publish 0.2.0 just switch to it.
```toml
teloc = { git = "https://github.com/p0lunin/teloc" }
```

**Pull request merged**
